---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart gunicorn
  systemd:
    name: gunicorn.service
    state: restarted

- name: restart celery
  systemd:
    name: celery.service
    state: restarted
