"""add schedule tables

Revision ID: 035e1d42485e
Revises: 319debadff64
Create Date: 2023-10-16 21:15:49.920351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035e1d42485e'
down_revision = '319debadff64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_text', sa.String(length=10000), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('schedule_creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pickr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pickr'
    )
    op.create_table('scheduled_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('generated_post_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime, nullable=False),
    sa.Column('tweet_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('celery_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['generated_post_id'], ['pickr.generated_post.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['pickr.schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pickr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pickr'
    )
    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickr_scheduled_post_generated_post_id'), ['generated_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickr_scheduled_post_schedule_id'), ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickr_scheduled_post_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_pickr_scheduled_post_generated_post_id'))

    op.drop_table('scheduled_post', schema='pickr')
    op.drop_table('schedule', schema='pickr')
    # ### end Alembic commands ###
