"""add post edit table

Revision ID: 319debadff64
Revises: abd484a34bfd
Create Date: 2023-10-14 14:40:41.292625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319debadff64'
down_revision = 'abd484a34bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_edit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('generated_post_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_post_id'], ['pickr.generated_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pickr.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pickr'
    )
    with op.batch_alter_table('post_edit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickr_post_edit_generated_post_id'), ['generated_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_edit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickr_post_edit_generated_post_id'))

    op.drop_table('post_edit', schema='pickr')
    # ### end Alembic commands ###
