"""twitter model

Revision ID: 5fb94ed2a466
Revises: 29f53a2e7e94
Create Date: 2024-01-05 00:03:19.303279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fb94ed2a466'
down_revision = '29f53a2e7e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('niche_id', sa.UUID(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('author_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('niche_id')
        batch_op.drop_column('published_at')

  

    # ### end Alembic commands ###
