"""scheduled fields

Revision ID: 69c51049ad4f
Revises: 7af9f621b76c
Create Date: 2023-10-24 20:41:07.693865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69c51049ad4f'
down_revision = '7af9f621b76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('week_number', sa.Integer(), nullable=True))
        batch_op.drop_column('schedule_text')
        batch_op.drop_column('schedule_creation_date')

    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_hour', sa.Integer(), nullable=True))
        batch_op.alter_column('scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.alter_column('scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('scheduled_hour')
        batch_op.drop_column('scheduled_day')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('schedule_text', sa.VARCHAR(length=10000), autoincrement=False, nullable=False))
        batch_op.drop_column('week_number')
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
