"""schedule page updates

Revision ID: 76563eee15af
Revises: df4c3ab833fd
Create Date: 2023-12-16 23:13:31.540313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76563eee15af'
down_revision = 'df4c3ab833fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('modeled_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trend_class', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_text', sa.String(length=10000), nullable=True))
  
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clean_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('clean_text')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('schedule_text')

    with op.batch_alter_table('modeled_topic', schema=None) as batch_op:
        batch_op.drop_column('trend_class')
    # ### end Alembic commands ###
