"""add reddit post fields

Revision ID: 7af9f621b76c
Revises: cab042341f2f
Create Date: 2023-10-21 15:21:40.369226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7af9f621b76c'
down_revision = 'cab042341f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_comments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('permalink', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit', schema=None) as batch_op:
        batch_op.drop_column('permalink')
        batch_op.drop_column('num_comments')
    # ### end Alembic commands ###
