"""Initial migration

Revision ID: 81c0c437eeeb
Revises: 
Create Date: 2023-07-15 22:23:02.701860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c0c437eeeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_id')
    with op.batch_alter_table('generated_post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'modeled_topic', ['modeled_topic_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('modeled_topic', schema=None) as batch_op:
        batch_op.drop_constraint('modeled_topic_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('stripe_subscription', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('tweet_modeled_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('tweet_modeled_topic_assoc_tweet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tweet', ['tweet_id'], ['id'], referent_schema='pickr')
        batch_op.create_foreign_key(None, 'modeled_topic', ['modeled_topic_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('user_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('user_topic_assoc_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'], referent_schema='pickr')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='pickr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_topic_assoc_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('tweet_modeled_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tweet_modeled_topic_assoc_tweet_id_fkey', 'tweet', ['tweet_id'], ['id'])

    with op.batch_alter_table('stripe_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('modeled_topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('modeled_topic_topic_id_fkey', 'topic', ['topic_id'], ['id'])

    with op.batch_alter_table('generated_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('tweet_id',
    sa.Column('modeled_topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('modeled_topic_id', name='tweet_id_pkey')
    )
    # ### end Alembic commands ###
