"""twitter model

Revision ID: b0c39a2094fc
Revises: 29f53a2e7e94
Create Date: 2024-01-04 22:54:53.117591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0c39a2094fc'
down_revision = '29f53a2e7e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niche_id', sa.UUID(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'niche', ['niche_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('tweet_modeled_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('tweet_modeled_topic_assoc_tweet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tweet_modeled_topic_assoc_modeled_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modeled_topic', ['modeled_topic_id'], ['id'], referent_schema='pickr')
        batch_op.create_foreign_key(None, 'tweet', ['tweet_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('twitter_term', schema=None) as batch_op:
        batch_op.drop_constraint('twitter_term_niche_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'niche', ['niche_id'], ['id'], referent_schema='pickr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twitter_term', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('twitter_term_niche_id_fkey', 'niche', ['niche_id'], ['id'])

    with op.batch_alter_table('tweet_modeled_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tweet_modeled_topic_assoc_modeled_topic_id_fkey', 'modeled_topic', ['modeled_topic_id'], ['id'])
        batch_op.create_foreign_key('tweet_modeled_topic_assoc_tweet_id_fkey', 'tweet', ['tweet_id'], ['id'])

    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('author_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('niche_id')
    # ### end Alembic commands ###
