"""Initial migration

Revision ID: ddfc2a57c302
Revises: 
Create Date: 2023-08-19 11:12:54.002281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfc2a57c302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_post', schema=None) as batch_op:
        batch_op.drop_constraint('generated_post_modeled_topic_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modeled_topic', ['modeled_topic_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('modeled_topic', schema=None) as batch_op:
        batch_op.drop_constraint('modeled_topic_niche_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'niche', ['niche_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('reddit', schema=None) as batch_op:
        batch_op.drop_constraint('reddit_modeled_topic_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reddit_subreddit_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modeled_topic', ['modeled_topic_id'], ['id'], referent_schema='pickr')
        batch_op.create_foreign_key(None, 'subreddit', ['subreddit_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('stripe_subscription', schema=None) as batch_op:
        batch_op.drop_constraint('stripe_subscription_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('subreddit', schema=None) as batch_op:
        batch_op.drop_constraint('subreddit_niche_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'niche', ['niche_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('tweet_modeled_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('tweet_modeled_topic_assoc_modeled_topic_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tweet_modeled_topic_assoc_tweet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modeled_topic', ['modeled_topic_id'], ['id'], referent_schema='pickr')
        batch_op.create_foreign_key(None, 'tweet', ['tweet_id'], ['id'], referent_schema='pickr')

    with op.batch_alter_table('user_niche_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('user_niche_assoc_niche_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_niche_assoc_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='pickr')
        batch_op.create_foreign_key(None, 'niche', ['niche_id'], ['id'], referent_schema='pickr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_niche_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_niche_assoc_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_niche_assoc_niche_id_fkey', 'niche', ['niche_id'], ['id'])

    with op.batch_alter_table('tweet_modeled_topic_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tweet_modeled_topic_assoc_tweet_id_fkey', 'tweet', ['tweet_id'], ['id'])
        batch_op.create_foreign_key('tweet_modeled_topic_assoc_modeled_topic_id_fkey', 'modeled_topic', ['modeled_topic_id'], ['id'])

    with op.batch_alter_table('subreddit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subreddit_niche_id_fkey', 'niche', ['niche_id'], ['id'])

    with op.batch_alter_table('stripe_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stripe_subscription_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('reddit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reddit_subreddit_id_fkey', 'subreddit', ['subreddit_id'], ['id'])
        batch_op.create_foreign_key('reddit_modeled_topic_id_fkey', 'modeled_topic', ['modeled_topic_id'], ['id'])

    with op.batch_alter_table('modeled_topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('modeled_topic_niche_id_fkey', 'niche', ['niche_id'], ['id'])

    with op.batch_alter_table('generated_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('generated_post_modeled_topic_id_fkey', 'modeled_topic', ['modeled_topic_id'], ['id'])

    # ### end Alembic commands ###
