---
## This playbook hardens the target server, creates admin users, and installs common system packages
##
## Usage: ansible-playbook ./playbook/secure.yaml --extra-vars "target=<target>"
##
- hosts: '{{ target }}'
  become: yes
  become_method: sudo
  vars:
    HASHED_ADMIN_PASSWORD: "$5$llRBt89yKD.B5rHS$Qo0YSgxKPW5F4AitsqFggqd/Fwo/CPmVWRwuzNtSHp5"
    security_ssh_port: "22"
    security_sshd_name: ssh
    security_ssh_config_path: /etc/ssh/sshd_config
    admin_users:
      - ajdee
      - meiji163
      - sang
      - nathan
      - nathan_francis
    packages:
      - build-essential
      - tree
      - vim
      - htop
      - zstd
      - tmux
      - ncurses-term
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
      - libpq-dev
  roles:
    - secure
    - users
