---
- name: Add Cloud Ops Agent to hosts
  hosts: database
  become: true
  roles:
  - role: google-cloud-ops-agents-ansible
    vars:
      agent_type: ops-agent

- name: Install postgres
  hosts: database
  become: yes
  vars:
    postgres_users_no_log: false
    postgresql_python_library: python3-psycopg2
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: trust }
      - { type: local, database: all, user: all, auth_method: md5 }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '172.89.196.114/32', auth_method: md5 }
    postgresql_global_config_options:
      - option: listen_addresses
        value: "*"
      - option: log_directory
        value: "/var/log/postgres"
    postgresql_users:
      - name: pickr_super
        # generate the password hash with
        # echo -n "md5"; echo -n "${PASSWORD}${USERNAME}" | md5sum
        password: "md54a6905f66fdfdbe3b696ca0a5b7240d0"
        db: pickr
        priv: "ALL"
      - name: pickr_rw
        password: "md5f54ec7b2d05041a56a045161fc63f490"
        db: pickr
    postgresql_databases:
      - name: pickr
        owner: pickr_super
  roles:
    - geerlingguy.postgresql

- name: Install redis
  # creates a systemd service called redis_6379
  vars:
    redis_version: 7.0.7
    redis_bind: 0.0.0.0
    redis_protected_mode: "no"
  roles:
    - davidwittman.redis
