---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    HASHED_ADMIN_PASSWORD: "$6$rounds=656000$L.grd68gu7SrrU9k$K/5n2Xb8/wpvY/yudgq7HjurhN0505ANgqWaWk2Q3FGa1CSoZsMdTFBmrQ32omhQU9rTK1HxhVul.0v99HXrt."
    security_ssh_port: "22"
    security_sshd_name: ssh
    security_ssh_config_path: /etc/ssh/sshd_config
    admin_users:
      - ajdee
      - meiji163
      - natha
      - sang
      - nathan
      - nathan_francis
    packages:
      - tree
      - nano
      - htop
      - tmux
      - ncurses-term
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
  roles:
    - secure
    - users

- hosts: database
  become: yes
  vars:
    ############ postgres ############
    postgres_users_no_log: false
    postgresql_python_library: python3-psycopg2
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: trust }
      - { type: local, database: all, user: all, auth_method: md5 }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
    postgresql_global_config_options:
      - option: listen_addresses
        value: "localhost,{{ ansible_host }}"
      - option: log_directory
        value: "/var/log/postgres"
    postgresql_users:
      - name: pickr_super
        # generate the password hash with
        # echo -n "md5"; echo -n "${PASSWORD}${USERNAME}" | md5sum
        password: "md54a6905f66fdfdbe3b696ca0a5b7240d0"
        db: pickr
        priv: "ALL"
      - name: pickr_rw
        password: "md5f54ec7b2d05041a56a045161fc63f490"
        db: pickr
    postgresql_databases:
      - name: pickr
        owner: pickr_super

    ############# redis  #############
    # creates a systemd service called redis_6379
    redis_version: 7.0.7
    redis_bind: 127.0.0.1
    redis_protected_mode: "no"

    ########## google cloud ##########
    # install ops-agent
    agent_type: ops-agent

  roles:
    - geerlingguy.postgresql
    - davidwittman.redis
    - google-cloud-ops-agent-ansible
