- hosts: worker
  become: yes
  vars:
    celery_user: "celery"
    celery_password: "celery"
    app_root: "/home/celery/topic-tweet"
    dotenv: "/home/celery/.env"

    CELERY_BIN: "/home/celery/venv/bin/celery"
    CELERY_APP: "pickr_flask.run_celery"
    CELERYD_NODES: "w1" # single worker node, multiple would be e.g. "w1 w2 w3"
    CELERYD_OPTS: "--time-limit=18000 --concurrency=2 -Q model_runner"
    CELERYD_LOG_LEVEL: "INFO"
    CELERYD_PID_FILE: "/var/log/celery/%n.pid"
    CELERYD_LOG_FILE: "/var/log/celery/%n%I.log"
  roles:
    - worker
